# PostgreSql Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6o62s7afjfc73aeq530-a.singapore-postgres.render.com/moneymanager_i9j5
spring.datasource.username=moneymanager_i9j5_user
spring.datasource.password=4QZGZXGuft1RkFh31v329kfhQblrz35U

logging.level.org.springframework.security=DEBUG