package com.codewithfaraz.moneymanager.controller;

import com.codewithfaraz.moneymanager.entity.ProfileEntity;
import com.codewithfaraz.moneymanager.service.*;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

@RestController
@RequestMapping("/email")
@RequiredArgsConstructor
public class EmailController {

    private final ExcelService excelService;
    private final IncomeService incomeService;
    private final ExpenseService expenseService;
    private final EmailService emailService;
    private final ProfileService profileService;

    // 1. Endpoint to email the Income Excel report
    @GetMapping("/income-excel")
    public ResponseEntity<Void> emailIncomeExcel() throws IOException {
        // Fetch the currently authenticated user's profile
        ProfileEntity profile = profileService.getCurrentProfile();

        // Generate the Excel file in memory rather than saving it to the disk
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        excelService.writeIncomesToExcel(
                byteArrayOutputStream,
                incomeService.getCurrentMonthIncomesForCurrentUser()
        );

        // Send the email with the generated byte array as an attachment
        emailService.sendEmailWithAttachment(
                profile.getEmail(),
                "Your income Excel report",
                "Please find attached your income report",
                byteArrayOutputStream.toByteArray(),
                "income.xlsx"
        );

        return ResponseEntity.ok(null);
    }

    // 2. Endpoint to email the Expense Excel report
    @GetMapping("/expense-excel")
    public ResponseEntity<Void> emailExpenseExcel() throws IOException {
        // Fetch the currently authenticated user's profile
        ProfileEntity profile = profileService.getCurrentProfile();

        // Generate the Excel file in memory
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        excelService.writeExpensesToExcel(
                byteArrayOutputStream,
                expenseService.getCurrentMonthExpensesForCurrentUser()
        );

        // Send the email with the generated byte array as an attachment
        emailService.sendEmailWithAttachment(
                profile.getEmail(),
                "Your expense Excel report",
                "Please find attached your expense report",
                byteArrayOutputStream.toByteArray(),
                "expense.xlsx"
        );

        return ResponseEntity.ok(null);
    }
}
